export const trainerQuotes = [
  { quote: "All right! Here I come! I'll show you my power!", trainer: "Youngster Ryan" },
  { quote: "Hi! I like shorts! They're comfy and easy to wear", trainer: "Youngster Owen" },
  { quote: "Haw haw haw... I'll show you how awesome my Pokémon are!", trainer: "Youngster Yoshihiro" },
  { quote: "Don't let your guard down, or you may be crying when a kid beats you.", trainer: "Youngster Isaac" },
  { quote: "I've raised my Pokémon with great care. You're not allowed to hurt them!", trainer: "Youngster Simppa" },
  { quote: "Let's have a fun Pokémon battle!", trainer: "Lass Viviane" },
  { quote: "I'll show you the ropes of how to really use Pokémon!", trainer: "Lass Seiko" },
  { quote: "A serious battle starts from a serious beginning! Are you sure you're ready?", trainer: "Lass Ernestine" },
  {
    quote: "I'm gaining as much experience as I can because I want to be a Gym Leader someday.",
    trainer: "Schoolboy Aloysius",
  },
  { quote: "We're about to battle, but that doesn't mean we can't be polite! Good luck!", trainer: "Schoolboy Declan" },
  { quote: "Hey! This is no laughing matter! We're about to battle!", trainer: "Schoolboy Jibade" },
  { quote: "I want to be a Pokémon researcher when I grow up.", trainer: "Schoolboy Kevin" },
  { quote: "Ah... You look strong... I hope I'll be all right...", trainer: "Schoolgirl Sophie" },
  {
    quote: "I'm good at the strategy and tactics of battles, but I'm bad at throwing Poké Balls!",
    trainer: "Schoolgirl Rumiko",
  },
  {
    quote:
      "I'm honestly not that good at Pokémon battles... When I think about my future, though, it seems like I have no choice but to battle!",
    trainer: "Schoolgirl Opeyemi",
  },
  { quote: "Grumble, grumble...", trainer: "Schoolgirl Eloise" },
  { quote: "Are you my opponent? You look kind of hungry.", trainer: "Rich Boy Franc" },
  { quote: "My mom chose my Pokémon. I don't think they'll lose to you.", trainer: "Rich Boy Sol" },
  { quote: "I am very strong. I will never lose.", trainer: "Preschooler Zak" },
  { quote: "No pouting when you lose, 'cause that's just lame.", trainer: "Preschooler Olivia" },
  {
    quote: "Um, this is what you call a battle, right? Why do we do stuff like this again?",
    trainer: "Preschooler Nadine",
  },
  { quote: "Hey! Welcome! I've got some real plump and lively Pokémon right here!", trainer: "Garcon Cole" },
  { quote: "Didn't you come here for a Pokémon battle?", trainer: "Waitress Ayu" },
  { quote: "I can't let Pokémon I really love battle.", trainer: "Poké Fan Gelar" },
  // { quote: "", trainer: "" },
  // { quote: "", trainer: "" },
  // { quote: "", trainer: "" },
  // { quote: "", trainer: "" },
  // { quote: "", trainer: "" },
];
